/** base */
export const technoList = [
  {
    id: 1,
    name: "Html",
    label: "Hyper Text Makup Language",
    link: "/",
    imgUrl: "/techno/html.png",
  },
  {
    id: 2,
    name: "Css",
    label: "Hyper Text Makup Language",
    link: "/",
    imgUrl: "/techno/css.png",
  },
  {
    id: 3,
    name: "Css",
    label: "Hyper Text Makup Language",
    link: "/",
    imgUrl: "/techno/js.png",
  },
  {
    id: 4,
    name: "Css",
    label: "Hyper Text Makup Language",
    link: "/",
    imgUrl: "/techno/ts.svg",
  },
  {
    id: 5,
    name: "Css",
    label: "Hyper Text Makup Language",
    link: "/",
    imgUrl: "/techno/git.png",
  },
  {
    id: 6,
    name: "Css",
    label: "Hyper Text Makup Language",
    link: "/",
    imgUrl: "/techno/github.svg",
  },
  {
    id: 7,
    name: "Css",
    label: "Hyper Text Makup Language",
    link: "/",
    imgUrl: "/techno/prisma.png",
  },
  {
    id: 8,
    name: "Css",
    label: "Hyper Text Makup Language",
    link: "/",
    imgUrl: "/techno/mysql.png",
  },
  {
    id: 9,
    name: "Css",
    label: "Hyper Text Makup Language",
    link: "/",
    imgUrl: "/techno/vscode.png",
  },
  {
    id: 10,
    name: "Css",
    label: "Hyper Text Makup Language",
    link: "/",
    imgUrl: "/techno/npm.png",
  },
  {
    id: 11,
    name: "Css",
    label: "Hyper Text Makup Language",
    link: "/",
    imgUrl: "/techno/yarn.png",
  },
  {
    id: 12,
    name: "Css",
    label: "Hyper Text Makup Language",
    link: "/",
    imgUrl: "/techno/pnpm.svg",
  },
  {
    id: 13,
    name: "Css",
    label: "Hyper Text Makup Language",
    link: "/",
    imgUrl: "/techno/react.png",
  },
  {
    id: 14,
    name: "Css",
    label: "Hyper Text Makup Language",
    link: "/",
    imgUrl: "/techno/redux.png",
  },
  {
    id: 15,
    name: "Css",
    label: "Hyper Text Makup Language",
    link: "/",
    imgUrl: "/techno/rquery.png",
  },
  {
    id: 16,
    name: "Css",
    label: "Hyper Text Makup Language",
    link: "/",
    imgUrl: "/techno/tailwind.jpeg",
  },
  {
    id: 17,
    name: "Css",
    label: "Hyper Text Makup Language",
    link: "/",
    imgUrl: "/techno/vite.png",
  },
  {
    id: 18,
    name: "Css",
    label: "Hyper Text Makup Language",
    link: "/",
    imgUrl: "/techno/next.png",
  },
  {
    id: 19,
    name: "Css",
    label: "Hyper Text Makup Language",
    link: "/",
    imgUrl: "/techno/MongoDB.jpeg",
  },
  {
    id: 20,
    name: "Css",
    label: "Hyper Text Makup Language",
    link: "/",
    imgUrl: "/techno/firebase.png",
  },
];
