import Footer from "@/components/Footer";
import "../globals.css";

export const metadata = {
  title: "h2g",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="p-0 m-0">
        {children}
        <Footer />
      </body>
    </html>
  );
}
